### ISSUE TITLE
eventOptionsApi should be true by default

### ISSUE THREAD

**Issue by franklx** [pipe01/esbuild-plugin-vue3#1]
In my opinion the [eventsOptionsApi](https://github.com/pipe01/esbuild-plugin-vue3/blob/33801c2b5adfd5b2a30ad48c7bccfb8de5359bcf/src/options.ts#L8) should be set to **true** by default or should be emphasized in ```README.md```.
I banged my head at this for hours trying to figure out the weird behavior of  [PrimeVue](https://github.com/primefaces/primevue)...
I bet that any framework out there needs the options API to be enabled!

**Comment by pipe01** [comment]
You're right, I didn't realize it could break stuff.
