### ISSUE TITLE
Please release the cssInline option

### ISSUE THREAD

**Issue by jonnitto** [pipe01/esbuild-plugin-vue3#22]
Thank you a lot for your package. When you will do a new release?

**Comment by muodov** [comment]
+1 to this. I understand that the plugin "is not thoroughly tested", but I'm using it in my hack project and `cssInline` would be really helpful

**Comment by NathanBeddoeWebDev** [comment]
https://github.com/pipe01/esbuild-plugin-vue3/pull/19 would also like the release done for this PR as well. It's been a long time waiting :')
