### ISSUE TITLE
Not support image handling

### ISSUE THREAD

**Issue by hiveer** [pipe01/esbuild-plugin-vue3#23]
I'm trying to import an image in SFC, but I got this error:
22:58:48 js.1   | ✘ [ERROR] Could not resolve "./images/opencsg_logo.png"

```
<script lang="ts" setup>
import { ref } from 'vue'
import logo from './images/logo.png'
</script>
```

not sure how does this plugin handle this?

**Comment by pipe01** [comment]
This seems like it should be handled by esbuild, not this plugin. For example, you could use [this plugin](https://www.npmjs.com/package/esbuild-plugin-inline-image).

**Comment by hiveer** [comment]
@pipe01 thanks for the suggestion
