### ISSUE TITLE
__VUE_PROD_HYDRATION_MISMATCH_DETAILS__ warning since vue version 3.4.*

### ISSUE THREAD

**Issue by andmm** [pipe01/esbuild-plugin-vue3#24]
Hello, since upgrading vue to latest version (3.4.15) I'm getting the following warning: 

![image](https://github.com/pipe01/esbuild-plugin-vue3/assets/4256677/cc140385-c0fd-4e68-a6b1-fa596e073271)

I've tried passing __VUE_PROD_HYDRATION_MISMATCH_DETAILS__ flag to the vuePlugin() options object but it didn't work. Checking the source for the Options.ts I don't think this flag has been implemented in this plugin since it's relatively new. 

Docs can be found here: https://vuejs.org/api/compile-time-flags

Am I doing something wrong?  Would appreciate the help. Cheers

**Comment by pipe01** [comment]
Thanks for reporting the issue, I added a new option that you can use to enable or disable this feature.

**Comment by andmm** [comment]
That was quick, thank you!.
